<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="estilo/estiloNovaMesa.css">

    <title>Mesas</title>
</head>
<body>
                                <!--Menu-->
    <div>
        <nav class="menu">
          <ul>
            <li>
              <img id="foto" class="nav-item" src="imagem/teste.jpg" width="40" height="40">
            </li>
            <li class="nav-item">
              <a href="teste">Home</a>
            </li>
            <li class="nav-item">
              <a href="teste">Pedido</a>
            </li>
            <li class="nav-item">
              <a href="teste">Produro</a>
            </li>
            <li class="nav-item">
              <a href="teste">Produto</a>
            </li>
            <li class="nav-item">
              <a href="teste">Mesa</a>
            </li>
            <li class="nav-item">
              <a href="teste">Estoque</a>
            </li>
            <li class="nav-item">
              <a href="teste">Funcionario</a>
            </li>
            <a href="sair"><img class="sair" src="imagem/teste.jpg" width="10" height="10"></a>
          </ul>

        </nav>  
    </div>
                                        <!--Meio da tela-->


    <p>Lanchonete - Nova Mesa</p>

    <div class="bordaMeio">                                     
      <form action="/salvarProduto" method="post">
              <input type="text" class="form-control" id="NumMesa" placeholder="N° Mesa" name="numMesa" value="0">
              
              <div class="form-group">
                  <input type="text" class="form-control" id="NumMesa" placeholder="N° Mesa" name="numMesa">
              </div>
              <br>
              <select name="status" id="statusMesa" >
                  <option value="mesa">Disponivel</option>
                  <option value="mesa">Ocupada</option>
              </select>
              <br> <br>
             <button type="submit" class="btnCad">Registrar Mesa </button>
          </form>
      </div>    


                        <!--Contato-->
    <div class="contato">
        <p>Lanchonete - Quick Snack - Central: 000000000</p>
    </div>


</body>
</html>